title: Ono Grindz Manoa
description: Making Food Choice Easier for the UH Community
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/onogrindzmanoa

gems:
  - jekyll-mentions
