title: Ono Grindz Manoa
description: Making Food Choice Easier for the UH Community
google_analytics: 
show_downloads: false
theme: jekyll-theme-caymangithub:
  repository_url: https://github.com/onogrindzmanoa/onogrindzmanoa.github.io

gems:
  - jekyll-mentions
