title: Ono Grindz Manoa
description: Making Food Choice Easier for the UH Community
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: true

gems:
  - jekyll-mentions
